apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
       app: postgre
    spec:
      containers:
        - name: postgre
          image: postgre:14.3
          ports:
            - containerPort: 5432
          env:
          - name: postgre_PASSWORD
            value: password
          - name: postgre_USER
            value: admin
          - name: postgre_DB
            value: database

---

apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
  -  port: 5432
     targetPort: 5432

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenews
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      labels:
       app: kubenews
    spec:
      containers:
        - name: kubenews
          image: caio/kubnews:v1
          env:
          - name: DB_DATABASE
            value: database
          - name: DB_USERNAME
            value: admin
          - name: DB_PASSWORD
            value: password
          - name: DB_HOST
            value: "postgre"

---

apiVersion: v1
kind: Service
metadata:
  name: kubenews-service
spec:
  selector:
    app: kubenews
  ports:
  -  port: 80
     targetPort: 8080
     nodePort: 30000
  type: LoadBalancer
  